import React from "react";

export default function Landing() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800">
      {/* HERO */}
      <section className="text-center py-20 px-6 bg-gradient-to-r from-teal-500 to-blue-600 text-white">
        <h1 className="text-5xl font-bold mb-4">TalkEasy</h1>
        <p className="text-xl max-w-2xl mx-auto">
          An AI-powered mental wellness platform that helps you talk openly,
          track emotions, build healthy habits and improve your mental
          wellbeing.
        </p>

        <div className="mt-8 flex justify-center gap-4">
          <a
            href="/dashboard"
            className="bg-white text-blue-600 px-6 py-3 rounded-xl font-semibold shadow"
          >
            Go to Dashboard
          </a>

          <a href="/login" className="border border-white px-6 py-3 rounded-xl">
            Login
          </a>
        </div>
      </section>

      {/* FEATURES */}
      <section className="py-20 px-6 max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">
          Platform Features
        </h2>

        <div className="grid md:grid-cols-3 gap-8">
          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">AI Therapist Chat</h3>
            <p>
              Talk with an AI therapist that listens to your problems and
              provides supportive responses and practical guidance.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">Mood Tracking</h3>
            <p>
              Track your emotional state daily and understand how your mood
              evolves over time.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">Habit Tracker</h3>
            <p>
              Build positive habits like meditation, exercise and journaling
              while monitoring your progress.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">Emotional History</h3>
            <p>
              View your past emotions, conversations and insights generated by
              the AI system.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">Statistics Dashboard</h3>
            <p>
              Visualize your mental wellness journey with graphs and progress
              insights.
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow">
            <h3 className="text-xl font-semibold mb-2">Multilingual Support</h3>
            <p>
              Use TalkEasy in multiple languages to make emotional support
              accessible for everyone.
            </p>
          </div>
        </div>
      </section>

      {/* FOUNDER */}
      <section className="py-20 bg-white text-center px-6">
        <h2 className="text-3xl font-bold mb-6">Meet the Founder</h2>

        <div className="max-w-3xl mx-auto">
          <h3 className="text-xl font-semibold text-blue-600 mb-3">
            Taha Shahud – Student Developer
          </h3>

          <p className="text-gray-600 mb-4">
            Taha Shahud is the creator of TalkEasy, an AI-powered mental
            wellness platform designed to support people through intelligent
            conversations, mood tracking, habit development and emotional
            analytics.
          </p>

          <p className="text-gray-600 mb-8">
            Currently pursuing studies at MGM University, Taha focuses on
            building technology that combines artificial intelligence with human
            wellbeing to solve real-world problems.
          </p>

          <div className="flex justify-center gap-4">
            <a
              href="https://taha-personal.netlify.app"
              target="_blank"
              className="bg-blue-600 text-white px-5 py-2 rounded-lg"
            >
              Portfolio
            </a>

            <a
              href="https://github.com/"
              target="_blank"
              className="bg-gray-800 text-white px-5 py-2 rounded-lg"
            >
              GitHub
            </a>

            <a
              href="https://linkedin.com/"
              target="_blank"
              className="bg-blue-700 text-white px-5 py-2 rounded-lg"
            >
              LinkedIn
            </a>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="text-center py-6 bg-gray-100 text-gray-500">
        © {new Date().getFullYear()} TalkEasy – Built by Taha Shahud
      </footer>
    </div>
  );
}
